// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebStudio.Application_core.Database_Context;

#nullable disable

namespace WebStudio.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20250423114414_InitialSeed")]
    partial class InitialSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebStudio.Application_core.Entities.Company", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Company Id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            id = new Guid("76032384-50ad-4903-9889-f0e95ac9eedf"),
                            Address = "75 Ogunnusi Road, Off Ojodu-Berger, Ogba, Lagos-State",
                            Country = "NIGERIA",
                            Name = "WALURE CAPITAL"
                        },
                        new
                        {
                            id = new Guid("8d19dc2d-f84a-4ddb-9980-5f9326661dd0"),
                            Address = "62 Ajayi Road, Ogba, Ikeja",
                            Country = "NIGERIA",
                            Name = "VISION STEP"
                        });
                });

            modelBuilder.Entity("WebStudio.Application_core.Entities.Employee", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Employee Id");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            id = new Guid("35a06106-30f5-44e1-8998-014fc629db35"),
                            Age = 22,
                            CompanyId = new Guid("76032384-50ad-4903-9889-f0e95ac9eedf"),
                            Name = "Ibirogba Taiwo",
                            Position = "Software Engineer"
                        },
                        new
                        {
                            id = new Guid("a780950f-9138-46c9-93aa-cec6c227f38a"),
                            Age = 25,
                            CompanyId = new Guid("76032384-50ad-4903-9889-f0e95ac9eedf"),
                            Name = "Mercy Vivian",
                            Position = "Software Engineer"
                        },
                        new
                        {
                            id = new Guid("b60d66c9-528e-4874-bad8-0c6e7e73bcbe"),
                            Age = 26,
                            CompanyId = new Guid("8d19dc2d-f84a-4ddb-9980-5f9326661dd0"),
                            Name = "Pearson Goodness",
                            Position = "Sales Person"
                        });
                });

            modelBuilder.Entity("WebStudio.Application_core.Entities.Employee", b =>
                {
                    b.HasOne("WebStudio.Application_core.Entities.Company", "company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("company");
                });

            modelBuilder.Entity("WebStudio.Application_core.Entities.Company", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
